### ISSUE TITLE
Can't connect wallet.

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#203] opened 2023-05-09 10:38 UTC
I couldn't connect my metamask wallet when I tried today.

Tried command-shift-r to refresh and clear the cache, but clicking on 'connect' in the top left did nothing.

https://github.com/playmint/ds/assets/129759334/5b783ca5-2926-4302-9850-a0fc650313c8

**Comment by PlaymintDavid** [comment] 2023-05-09 11:03
Reopening chrome fixed it.

I think the bug is caused when the game thinks metamask is open but it's actually not. If possible, could 'connect' switch focus to Metamask, ensuring it's visible?

**Comment by chrisfarms** [comment] 2023-05-09 12:11
potential duplicate of: https://github.com/playmint/ds/issues/176

> If possible, could 'connect' switch focus to Metamask, ensuring it's visible?

it's not possible to trigger focusing metamask unfortunately ... if there is already a metamask prompt in the background (indicated by a little number of the browser extension's icon), then there is nothing we are able to do to bring that to the foreground.

**Comment by PlaymintDavid** [comment] 2023-05-09 13:03
Understood. No worries.

I assumed it was because there was a prompt in the background but there wasn't. Sounds like a metamask problem.

**Comment by ldunnplaymint** [comment] 2023-05-10 08:45
Closed as Duplicate

**Closed by ldunnplaymint** 2023-05-10 08:45 UTC
