### ISSUE TITLE
Can't move due to failed SCOUT_SEEKER

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#143] opened 2023-04-15 09:22 UTC
Not sure I quite have steps to reproduce, but...

At some point when I was scouting I double-clicked. It brought up a GraphQL error. Subsequently, when I try and move it fails, throwing up a failed SCOUT_SEEKER, despite the fact I was moving not scouting.

https://user-images.githubusercontent.com/129759334/232205245-b11622bf-31be-4a6e-ae18-b43e6341c019.mov

**Comment by PlaymintDavid** [comment] 2023-04-15 09:27
Refreshing the page fixes it.

**Comment by chrisfarms** [comment] 2023-04-15 09:37
believe this is a duplicate of: https://github.com/playmint/ds/issues/123

**Closed** 2023-04-24 12:25 UTC
