### ISSUE TITLE
Constructing doesn't work on the first session

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#166] opened 2023-04-26 11:59 UTC
You can click the Construct button, but when you select a tile the right-panel doesn't give any construct options

Is fixed by refreshing the page

**Comment by ldunnplaymint** [comment] 2023-04-26 14:11
Closed as a dupe of https://github.com/playmint/ds/issues/130

**Closed by ldunnplaymint** 2023-04-26 14:11 UTC
