### ISSUE TITLE
Connect button does not reappear if the user switches to an unconnected metamask account

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#175] opened 2023-04-27 08:48 UTC
Set up:
Have two metamask accounts, opens the game and connects one account only.

If the user switches from a connected meta mask account to an unconnected one, the shell does not pick up on it and will not flip the state into the "not connected" state.

**Comment by chrisfarms** [comment] 2023-04-28 08:20
this will be a wontfix unfortunately.

[EIP1193](https://eips.ethereum.org/EIPS/eip-1193) wallets do not expose any event or api to detect that you have selected a non-connected account, so it is impossible to detect this situation by design. The only scenario where the connect button will ever display is when there are zero connected accounts.

The selected wallet in the metamask UI != the connected account in the site. It's unfortunately just a bit of poor UX.

**Closed by chrisfarms** 2023-04-28 08:20 UTC
